#!/bin/sh /etc/rc.common

USE_PROCD=1
START=50
STOP=50

PROG=/usr/sbin/mwlwifi_thaw_clients.sh
NAME=mwlwifi_thaw_clients
INSTANCE=master

start_service()
{
    procd_open_instance $INSTANCE
    procd_set_param command $PROG
    procd_set_param stdout 1
    procd_close_instance $INSTANCE
}

stop_service()
{
    procd_send_signal $NAME $INSTANCE 10
}
